name: Padavan编译PSG1218 HuangYingNing 

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
    paths:
      - 'HuangYingNing'
#  push:
#    tags:
#    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 17 * * 4

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: 部署系统
      uses: actions/checkout@master
    - name: 安装软件
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        #sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev \
        gcc-multilib
    - name: 下载源码
      run: |
        mkdir -p /opt/Padavan
        mkdir -p /opt/rt-n56u
        git clone https://github.com/HuangYingNing/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        ./clean_toolchain
        ./build_toolchain
    - name: 编译固件
      run: |
        sudo rm /opt/rt-n56u/trunk/configs/templates/PSG1218.config
        cp HuangYingNing /opt/rt-n56u/trunk/configs/templates/PSG1218.config
        sudo chmod 777 /opt/rt-n56u/trunk/configs/templates/PSG1218.config
        cd /opt/rt-n56u/trunk
        sudo ./clear_tree
        sudo ./build_firmware_modify PSG1218
        sudo mv -f images/*.trx /opt/Padavan/
        cp -f .config /opt/Padavan/PSG1218.config
    - name : 上传固件
      uses: actions/upload-artifact@master
      with:
        name: Padavan-MT7620_h
        path: /opt/Padavan
